import type { Act, City, GameState, Performer } from "./types";

export const CITIES: City[] = [
    {
        id: "krakow",
        name: "Kraków",
        population: "804k",
        x: 53,
        y: 81,
        rent: 650,
        appeal: 1.1,
        weather: "sun",
        description: "A warm welcome beneath the old town rooftops.",
    },
    {
        id: "wroclaw",
        name: "Wrocław",
        population: "674k",
        x: 34,
        y: 69,
        rent: 550,
        appeal: 1.04,
        weather: "sun",
        description: "A city of bridges, curious crowds, and little surprises.",
    },
    {
        id: "poznan",
        name: "Poznań",
        population: "541k",
        x: 34,
        y: 44,
        rent: 500,
        appeal: 1,
        weather: "cloud",
        description: "Make every złoty count in this lively market city.",
    },
    {
        id: "gdansk",
        name: "Gdańsk",
        population: "486k",
        x: 43,
        y: 15,
        rent: 700,
        appeal: 1.18,
        weather: "cloud",
        description: "Sea breezes and summer visitors fill the waterfront.",
    },
    {
        id: "warsaw",
        name: "Warszawa",
        population: "1.86m",
        x: 68,
        y: 43,
        rent: 950,
        appeal: 1.3,
        weather: "sun",
        description: "Bright lights, bigger crowds, and fierce competition.",
    },
    {
        id: "lodz",
        name: "Łódź",
        population: "655k",
        x: 51,
        y: 51,
        rent: 450,
        appeal: 0.96,
        weather: "rain",
        description: "A creative city with a soft spot for a daring act.",
    },
    {
        id: "lublin",
        name: "Lublin",
        population: "331k",
        x: 73,
        y: 66,
        rent: 400,
        appeal: 1.06,
        weather: "sun",
        description: "A city of circus lovers, where a good show travels far.",
    },
    {
        id: "szczecin",
        name: "Szczecin",
        population: "391k",
        x: 26,
        y: 30,
        rent: 400,
        appeal: 0.94,
        weather: "rain",
        description: "A riverside stop with room for an up-and-coming troupe.",
    },
];

export const PERFORMERS: Performer[] = [
    {
        id: "zofia",
        name: "Zofia Kowalska",
        role: "Aerial acrobat",
        kind: "acrobat",
        skill: 76,
        energy: 92,
        morale: 84,
        wage: 240,
        hired: true,
        costume: false,
        color: "#bfe4d6",
    },
    {
        id: "felix",
        name: "Felix Nowak",
        role: "Master juggler",
        kind: "juggler",
        skill: 68,
        energy: 88,
        morale: 90,
        wage: 180,
        hired: true,
        costume: false,
        color: "#f1d497",
    },
    {
        id: "bruno",
        name: "Bruno “Bubbles”",
        role: "Clown & crowd favorite",
        kind: "clown",
        skill: 72,
        energy: 95,
        morale: 94,
        wage: 160,
        hired: true,
        costume: false,
        color: "#ebbbab",
    },
    {
        id: "luna",
        name: "Luna Moreau",
        role: "Illusionist",
        kind: "magic",
        skill: 83,
        energy: 100,
        morale: 85,
        wage: 320,
        hired: false,
        costume: false,
        color: "#c9c2e5",
    },
    {
        id: "ada",
        name: "Ada Zielińska",
        role: "Tightrope artist",
        kind: "acrobat",
        skill: 81,
        energy: 100,
        morale: 88,
        wage: 280,
        hired: false,
        costume: false,
        color: "#b8d8e3",
    },
];

export const ACTS: Act[] = [
    {
        id: "silks",
        name: "A little closer to the stars",
        performerId: "zofia",
        kind: "acrobat",
        duration: 30,
        excitement: 86,
    },
    {
        id: "juggling",
        name: "Everything up in the air",
        performerId: "felix",
        kind: "juggler",
        duration: 30,
        excitement: 70,
    },
    {
        id: "clown",
        name: "The wonderfully wrong show",
        performerId: "bruno",
        kind: "clown",
        duration: 30,
        excitement: 62,
    },
    {
        id: "break",
        name: "Popcorn & a little breather",
        performerId: "",
        kind: "break",
        duration: 20,
        excitement: 0,
    },
    {
        id: "magic",
        name: "Now you see it…",
        performerId: "luna",
        kind: "magic",
        duration: 35,
        excitement: 90,
    },
    {
        id: "tightrope",
        name: "Walking on a whisper",
        performerId: "ada",
        kind: "acrobat",
        duration: 30,
        excitement: 93,
    },
    {
        id: "encore",
        name: "One last impossible catch",
        performerId: "felix",
        kind: "juggler",
        duration: 20,
        excitement: 78,
    },
];

export const INITIAL_STATE: GameState = {
    version: 1,
    circusName: "The Wandering Wonder",
    day: 1,
    hour: 9,
    money: 12000,
    fuel: 85,
    water: 100,
    reputation: 0,
    cityId: "krakow",
    route: ["wroclaw", "poznan", "gdansk"],
    setup: false,
    ticketPrice: 35,
    marketing: { posters: 0, radio: 0, social: 0 },
    performers: PERFORMERS,
    lineup: ["juggling", "clown", "break", "silks"],
    grounds: [
        { id: "tent", kind: "tent", x: 51, y: 43 },
        { id: "wagon", kind: "wagon", x: 24, y: 70 },
        { id: "generator", kind: "generator", x: 76, y: 70 },
    ],
    upgrades: [],
    history: [],
    log: ["Welcome to Kraków. Your first audience is waiting."],
    liveShow: null,
    lastResult: null,
    season: 1,
    gameOver: false,
};
