import type { ActDef, BuildingDef, Person } from "./types";

export const BUILDINGS: BuildingDef[] = [
    {
        kind: "smallTent",
        name: "Little big top",
        category: "Shows",
        width: 3,
        height: 3,
        cost: 2400,
        upkeep: 45,
        capacity: 80,
        power: 3,
        color: "#db7052",
        description:
            "An intimate 80-seat stage. Needs a technician, power, water and a connected path.",
    },
    {
        kind: "bigTop",
        name: "Grand pavilion",
        category: "Shows",
        width: 4,
        height: 4,
        cost: 5800,
        upkeep: 90,
        capacity: 180,
        power: 5,
        color: "#dfad4f",
        description: "180 seats and rigging for aerial acts. Needs a technician, power and water.",
    },
    {
        kind: "trailer",
        name: "Living trailer",
        category: "Backstage",
        width: 2,
        height: 2,
        cost: 950,
        upkeep: 12,
        beds: 4,
        power: 1,
        color: "#71a9a1",
        description:
            "Four assigned beds. Connected, serviced homes restore energy; generators nearby disturb sleep.",
    },
    {
        kind: "generator",
        name: "Generator",
        category: "Backstage",
        width: 2,
        height: 2,
        cost: 800,
        upkeep: 10,
        range: 6,
        color: "#83939a",
        description:
            "Supplies 10 power within 6 tiles. Uses 4 fuel per day. Keep at least 4 tiles from bedrooms.",
    },
    {
        kind: "waterTank",
        name: "Water tower",
        category: "Backstage",
        width: 1,
        height: 1,
        cost: 450,
        upkeep: 5,
        range: 6,
        color: "#77bacb",
        description: "Supplies water within 6 tiles. Tanks share the daily water stock.",
    },
    {
        kind: "toilets",
        name: "Washrooms",
        category: "Guest services",
        width: 1,
        height: 2,
        cost: 550,
        upkeep: 8,
        color: "#a1b383",
        description: "Connected, watered washrooms improve guest comfort.",
    },
    {
        kind: "popcorn",
        name: "Popcorn cart",
        category: "Guest services",
        width: 2,
        height: 1,
        cost: 650,
        upkeep: 9,
        power: 1,
        color: "#e7b866",
        description:
            "Earns extra income from show visitors. Assign a vendor; needs power and water.",
    },
    {
        kind: "lemonade",
        name: "Lemonade stand",
        category: "Guest services",
        width: 1,
        height: 1,
        cost: 400,
        upkeep: 6,
        color: "#c7ca72",
        description: "A refreshing extra purchase. Assign a vendor and connect water.",
    },
    {
        kind: "carousel",
        name: "Carousel",
        category: "Guest services",
        width: 2,
        height: 2,
        cost: 1600,
        upkeep: 20,
        power: 2,
        color: "#c28ca5",
        description: "A staffed, powered attraction. Increases comfort and visitor spending.",
    },
    {
        kind: "bench",
        name: "Park bench",
        category: "Scenery",
        width: 1,
        height: 1,
        cost: 90,
        upkeep: 1,
        color: "#bc8d65",
        description: "A connected resting place improves comfort near a tent.",
    },
    {
        kind: "flowers",
        name: "Flower garden",
        category: "Scenery",
        width: 1,
        height: 1,
        cost: 60,
        upkeep: 1,
        color: "#d9a2a8",
        description:
            "Adds a little delight when placed within 5 tiles of a tent and beside a path.",
    },
];
export const ACTS: ActDef[] = [
    {
        id: "clown",
        name: "A wonderfully bad idea",
        role: "clown",
        duration: 25,
        excitement: 46,
        energy: 12,
    },
    {
        id: "juggling",
        name: "Everything in the air",
        role: "juggler",
        duration: 25,
        excitement: 62,
        energy: 15,
    },
    {
        id: "acrobatics",
        name: "A balancing act",
        role: "acrobat",
        duration: 25,
        excitement: 75,
        energy: 18,
    },
    {
        id: "magic",
        name: "Now you see it",
        role: "magician",
        duration: 25,
        excitement: 72,
        energy: 14,
    },
    {
        id: "aerial",
        name: "Above the ordinary",
        role: "acrobat",
        duration: 30,
        excitement: 94,
        energy: 24,
        requiresBigTop: true,
    },
    {
        id: "interval",
        name: "Intermission",
        role: "interval",
        duration: 15,
        excitement: 0,
        energy: 0,
    },
];
const people: [string, string, Person["role"], number, number, string][] = [
    ["mila", "Mila Bell", "clown", 62, 95, "#e4a871"],
    ["otto", "Otto Finch", "juggler", 66, 110, "#77bab5"],
    ["inez", "Inez Vega", "acrobat", 72, 135, "#caa1c8"],
    ["ada", "Ada Moon", "magician", 76, 145, "#ada5d5"],
    ["felix", "Felix Reed", "technician", 70, 85, "#89a6b7"],
    ["bea", "Bea Bloom", "vendor", 68, 70, "#d1b977"],
    ["leo", "Leo Moss", "technician", 65, 80, "#95bfa0"],
    ["nora", "Nora Page", "vendor", 74, 80, "#e59b98"],
    ["luca", "Luca Star", "acrobat", 61, 105, "#a7bfde"],
    ["poppy", "Poppy Pip", "clown", 69, 115, "#e2bcca"],
];
export const CANDIDATES: Person[] = people.map(([id, name, role, skill, wage, color]) => ({
    id,
    name,
    role,
    skill,
    wage,
    hireCost: wage * 2,
    color,
    energy: 100,
    morale: 80,
    hired: false,
    homeId: null,
    assignmentId: null,
}));
export const buildingDef = (kind: BuildingDef["kind"]) => BUILDINGS.find((b) => b.kind === kind)!;
